### PR TITLE
update xls34 definitions

### PR DESCRIPTION
**Pull request by dangell7**

### CODE REVIEW

**Review by khancode — APPROVED** [review]

**Comment by khancode** [comment]
Can you resolve the merge conflicts and then I'll approve?

**Review by khancode — CHANGES_REQUESTED** [review]
Can you resolve the merge conflicts and then I'll approve?

**Comment by dangell7** [comment]
```
[
      "DiscountedFee",
      {
        "nth": 48,
        "isVLEncoded": false,
        "isSerialized": true,
        "isSigningField": true,
        "type": "UInt32"
      }
    ],
```

Doesn't exist anymore right? So that needs to be removed.

**Comment by khancode** [comment]
> ```
> [
>       "DiscountedFee",
>       {
>         "nth": 48,
>         "isVLEncoded": false,
>         "isSerialized": true,
>         "isSigningField": true,
>         "type": "UInt32"
>       }
>     ],
> ```
> 
> Doesn't exist anymore right? So that needs to be removed.

No it still exists, it needs to be changed to 49.

**Review by khancode — APPROVED** [review]
LGTM :)

**Pull request merged**
