### PR TITLE
merge develop into master

### PR DESCRIPTION
**Pull request by ledhed2222**
## High Level Overview of Change
 title says it all, but covers past merges into develop which moved the `docs` folder to the top, updated `HISTORY` files to account for latest release.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [x] Release

### CODE REVIEW

**Comment by intelliot** [comment]
There should not be a need to merge develop into master. We should be able to just fast forward master to match develop. It's effectively just a rename

**Review by JST5000 — APPROVED** [review]

**Comment by JST5000** [comment]
> There should not be a need to merge develop into master. We should be able to just fast forward master to match develop. It's effectively just a rename

I think this might be referring to something different than you think - this is to move some docs, update the release steps, and update history.md (Not to remove the `develop` branch) - Or maybe I'm misinterpretting your commment?

**Comment by intelliot** [comment]
> title says it all

This is a bad overview because the title definitely does not say it all

**Comment by intelliot** [comment]
> I think this might be referring to something different than you think - this is to move some docs, update the release steps, and update history.md (Not to remove the `develop` branch) - Or maybe I'm misinterpretting your commment?

Indeed, you are misinterpreting my comment.

Also, in the future, PRs should explain the reason *why* - i.e. why do you want to merge develop into master? What's the motivation and what's the benefit?

We can explain next week

**Pull request merged**
