### PR TITLE
chore: remove ripple-lib-transactionparser

### PR DESCRIPTION
**Pull request by mvadari**
## High Level Overview of Change

Title says it all.

### Context of Change

Package wasn't being used anymore

### Type of Change

- [x] Refactor (non-breaking change that only restructures code)

## Test Plan

CI passes.

### CODE REVIEW

**Comment by natenichols** [comment]
Do we want to wait on this to address Rome's feedback? I know he requested we maintain this functionality in 2.0.

**Review by natenichols — APPROVED** [review]
One comment. If we want to keep this functionality then my approval doesnt matter. 

If we end up removing it, this PR LGTM.

**Review by JST5000 — APPROVED** [review]
Change looks good pending decision above.

**Comment by mvadari** [comment]
> Do we want to wait on this to address Rome's feedback? I know he requested we maintain this functionality in 2.0.

We wanted to get rid of these packages anyways. I think if we want this functionality, we should rewrite it anyways, directly in the library.

**Pull request merged**
