### PR TITLE
removed console.warn for partial payment

### PR DESCRIPTION
**Pull request by Mwni**
https://github.com/XRPLF/xrpl.js/issues/1783

### CODE REVIEW

**Review by intelliot — APPROVED** [review]
Agree. It's bad practice for a library to call `console.warn`

**Review by ledhed2222 — APPROVED** [review]

**Review by mvadari — CHANGES_REQUESTED** [review]
Let's use `client.connection.trace` to log this instead of `console.warn`

**Comment by Mwni** [comment]
@mvadari This is already the case

**Comment by mvadari** [comment]
> @mvadari This is already the case

You're right, I forgot the code that I wrote lol

**Review by mvadari — APPROVED** [review]

**Comment by JST5000** [comment]
@Mwni Is this PR good to merge?

**Comment by Mwni** [comment]
@JST5000 Absolutely

**Comment by mvadari** [comment]
This merge conflict will require some work, because of the monorepo changes. But shouldn't be too hard because this change is tiny.

**Comment by Mwni** [comment]
What's the status on this?

**Comment by mvadari** [comment]
Hi @Mwni - you'll have to rebase this change before we can deploy it, because we don't have access to your fork.

Please also edit the CHANGELOG.

**Comment by intelliot** [comment]
Merged by #1896

**Comment by Mwni** [comment]
Oh hey, apologies for not rebasing in time

**Pull request closed without merging**
