### PR TITLE
chore: merge main into 3.0

### PR DESCRIPTION
**Pull request by ckniffen**
## High Level Overview of Change

Merge in a bunch of changes from main

### CODE REVIEW

**Comment by ckniffen** [comment]
This will fix failing check tests and update a bunch of dependencies

**Comment by ckniffen** [comment]
@JST5000 Is this a similar technique you used for xrpl-py@2.0?  I have never setup auto merges on github before only bitbucket.

**Review by JST5000 — APPROVED** [review]

**Comment by JST5000** [comment]
> @JST5000 Is this a similar technique you used for xrpl-py@2.0? I have never setup auto merges on github before only bitbucket.

I'm not sure about auto-merges. For the final merge back into main, we'll need to rebase from 3.0 and drop all the merge commits, but for now I think it's fine to merge in. @mvadari would know better than I do I think :)

**Comment by mvadari** [comment]
> > @JST5000 Is this a similar technique you used for xrpl-py@2.0? I have never setup auto merges on github before only bitbucket.
> 
> I'm not sure about auto-merges. For the final merge back into main, we'll need to rebase from 3.0 and drop all the merge commits, but for now I think it's fine to merge in. @mvadari would know better than I do I think :)

What we did for xrpl-py@2.0 was:
1. Rebase the branch on top of `main`
2. Merge the branch into `main` with `--ff-only` locally
3. Push the changes (with `main` branch protections temporarily turned off)

The `--ff-only` part is the important one, so that you preserve all the commits and hashes.

**Comment by ckniffen** [comment]
> > > @JST5000 Is this a similar technique you used for xrpl-py@2.0? I have never setup auto merges on github before only bitbucket.
> > 
> > 
> > I'm not sure about auto-merges. For the final merge back into main, we'll need to rebase from 3.0 and drop all the merge commits, but for now I think it's fine to merge in. @mvadari would know better than I do I think :)
> 
> What we did for xrpl-py@2.0 was:
> 
> 1. Rebase the branch on top of `main`
> 2. Merge the branch into `main` with `--ff-only` locally
> 3. Push the changes (with `main` branch protections temporarily turned off)
> 
> The `--ff-only` part is the important one, so that you preserve all the commits and hashes and avoid the merge commits.

Gotcha.

**Review by justinr1234 — APPROVED** [review]

**Pull request merged**
