### PR TITLE
Allow customized headers

### PR DESCRIPTION
**Pull request by JST5000**
## High Level Overview of Change

Allow users to customize the headers field in the client connection to provide api keys.

### Context of Change

In response to #2034 

### Type of Change

- [X] New feature (non-breaking change which adds functionality)

## Before / After

You can now add a custom header if you want.

## Test Plan

CI passes

### CODE REVIEW

**Review by ckniffen — APPROVED** [review]
I would only suggest a test and documentation of the feature

**Review by khancode — APPROVED** [review]
Agree with Caleb on adding documentation for this.

**Comment by vietnamese-chowder** [comment]
Regarding documentation, how about the following for `docs/interfaces/ClientOptions.html`?

```
<!DOCTYPE html><html class="default"><head> <meta charSet="utf-8"/> <meta http-equiv="x-ua-compatible" content="IE=edge"/> <title>ClientOptions | xrpl</title> <meta name="description" content="Documentation for xrpl"/> <meta name="viewport" content="width=device-width, initial-scale=1"/> <link rel="stylesheet" href="../assets/style.css"/> <link rel="stylesheet" href="../assets/highlight.css"/> <script async src="../assets/search.js" id="search-script"></script></head><body><script>document.body.classList.add(localStorage.getItem("tsd-theme") || "os")</script><header> <div class="tsd-page-toolbar"> <div class="container"> <div class="table-wrap"> <div class="table-cell" id="tsd-search" data-base=".."> <div class="field"><label for="tsd-search-field" class="tsd-widget search no-caption">Search</label><input type="text" id="tsd-search-field"/></div> <ul class="results"> <li class="state loading">Preparing search index...</li> <li class="state failure">The search index is not available</li> </ul> <a href="../index.html" class="title">xrpl</a> </div> <div class="table-cell" id="tsd-widgets"> <div id="tsd-filter"> <a href="#" class="tsd-widget options no-caption" data-toggle="options">Options</a> <div class="tsd-filter-group"> <div class="tsd-select" id="tsd-filter-visibility"> <span class="tsd-select-label">All</span> <ul class="tsd-select-list"> <li data-value="public">Public</li> <li data-value="protected">Public/Protected</li> <li data-value="private" class="selected">All</li> </ul> </div> <input type="checkbox" id="tsd-filter-inherited" checked/><label class="tsd-widget" for="tsd-filter-inherited">Inherited</label><input type="checkbox" id="tsd-filter-externals" checked/><label class="tsd-widget" for="tsd-filter-externals">Externals</label> </div> </div> <a href="#" class="tsd-widget menu no-caption" data-toggle="menu">Menu</a> </div> </div> </div> </div> <div class="tsd-page-title"> <div class="container"> <ul class="tsd-breadcrumb"> <li><a href="../modules.html">xrpl</a></li> <li><a href="ClientOptions.html">ClientOptions</a></li> </ul> <h1>Interface ClientOptions </h1> </div> </div></header><div class="container container-main"> <div class="row"> <div class="col-8 col-content"> <section class="tsd-panel tsd-hierarchy"> <h3>Hierarchy</h3> <ul class="tsd-hierarchy"> <li> <span class="tsd-signature-type">ConnectionUserOptions</span> <ul class="tsd-hierarchy"> <li><span class="target">ClientOptions</span></li> </ul> </li> </ul> </section> <section class="tsd-panel-group tsd-index-group"> <h2>Index</h2> <section class="tsd-panel tsd-index-panel"> <div class="tsd-index-content"> <section class="tsd-index-section "> <h3>Properties</h3> <ul class="tsd-index-list"> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#authorization" class="tsd-kind-icon">authorization</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#certificate" class="tsd-kind-icon">certificate</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#connectionTimeout" class="tsd-kind-icon">connection<wbr/>Timeout</a></li> <li class="tsd-kind-property tsd-parent-kind-interface"><a href="ClientOptions.html#feeCushion" class="tsd-kind-icon">fee<wbr/>Cushion</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#headers" class="tsd-kind-icon">headers</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#key" class="tsd-kind-icon">key</a></li> <li class="tsd-kind-property tsd-parent-kind-interface"><a href="ClientOptions.html#maxFeeXRP" class="tsd-kind-icon">max<wbr/>FeeXRP</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#passphrase" class="tsd-kind-icon">passphrase</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-overwrite"><a href="ClientOptions.html#proxy" class="tsd-kind-icon">proxy</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#proxyAuthorization" class="tsd-kind-icon">proxy<wbr/>Authorization</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-overwrite"><a href="ClientOptions.html#timeout" class="tsd-kind-icon">timeout</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#trace" class="tsd-kind-icon">trace</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#trustedCertificates" class="tsd-kind-icon">trusted<wbr/>Certificates</a></li> </ul> </section> </div> </section> </section> <section class="tsd-panel-group tsd-member-group "> <h2>Properties</h2> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"> <a id="authorization" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> authorization <a href="#authorization" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">authorization<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">string</span></div> <aside class="tsd-sources"> <p>Inherited from ConnectionUserOptions.authorization</p> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/connection.ts#L31">packages/xrpl/src/client/connection.ts:31</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"> <a id="certificate" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> certificate <a href="#certificate" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">certificate<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">string</span></div> <aside class="tsd-sources"> <p>Inherited from ConnectionUserOptions.certificate</p> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/connection.ts#L35">packages/xrpl/src/client/connection.ts:35</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"> <a id="connectionTimeout" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> connection<wbr/>Timeout <a href="#connectionTimeout" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">connection<wbr/>Timeout<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">number</span></div> <aside class="tsd-sources"> <p>Inherited from ConnectionUserOptions.connectionTimeout</p> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/connection.ts#L38">packages/xrpl/src/client/connection.ts:38</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface"> <a id="feeCushion" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> fee<wbr/>Cushion <a href="#feeCushion" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">fee<wbr/>Cushion<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">number</span></div> <aside class="tsd-sources"> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/index.ts#L117">packages/xrpl/src/client/index.ts:117</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"> <a id="headers" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> headers <a href="#headers" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">headers<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">{ [key: string]: string }</span></div> <aside class="tsd-sources"> <p>Inherited from ConnectionUserOptions.headers</p> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/connection.ts#L39">packages/xrpl/src/client/connection.ts:39</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"> <a id="key" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> key <a href="#key" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">key<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">string</span></div> <aside class="tsd-sources"> <p>Inherited from ConnectionUserOptions.key</p> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/connection.ts#L33">packages/xrpl/src/client/connection.ts:33</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface"> <a id="maxFeeXRP" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> max<wbr/>FeeXRP <a href="#maxFeeXRP" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">max<wbr/>FeeXRP<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">string</span></div> <aside class="tsd-sources"> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/index.ts#L118">packages/xrpl/src/client/index.ts:118</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"> <a id="passphrase" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> passphrase <a href="#passphrase" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">passphrase<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">string</span></div> <aside class="tsd-sources"> <p>Inherited from ConnectionUserOptions.passphrase</p> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/connection.ts#L34">packages/xrpl/src/client/connection.ts:34</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface tsd-is-overwrite"> <a id="proxy" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> proxy <a href="#proxy" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">proxy<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">string</span></div> <aside class="tsd-sources"> <p>Overrides ConnectionUserOptions.proxy</p> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/index.ts#L119">packages/xrpl/src/client/index.ts:119</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"> <a id="proxyAuthorization" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> proxy<wbr/>Authorization <a href="#proxyAuthorization" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">proxy<wbr/>Authorization<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">string</span></div> <aside class="tsd-sources"> <p>Inherited from ConnectionUserOptions.proxyAuthorization</p> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/connection.ts#L30">packages/xrpl/src/client/connection.ts:30</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface tsd-is-overwrite"> <a id="timeout" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> timeout <a href="#timeout" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">timeout<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">number</span></div> <aside class="tsd-sources"> <p>Overrides ConnectionUserOptions.timeout</p> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/index.ts#L120">packages/xrpl/src/client/index.ts:120</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"> <a id="trace" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> trace <a href="#trace" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">trace<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">boolean</span><span class="tsd-signature-symbol"> | </span><span class="tsd-signature-symbol">(</span><span class="tsd-signature-symbol">(</span>id<span class="tsd-signature-symbol">: </span><span class="tsd-signature-type">string</span>, message<span class="tsd-signature-symbol">: </span><span class="tsd-signature-type">string</span><span class="tsd-signature-symbol">)</span><span class="tsd-signature-symbol"> =&gt; </span><span class="tsd-signature-type">void</span><span class="tsd-signature-symbol">)</span></div> <aside class="tsd-sources"> <p>Inherited from ConnectionUserOptions.trace</p> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/connection.ts#L28">packages/xrpl/src/client/connection.ts:28</a></li> </ul> </aside> </section> <section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"> <a id="trustedCertificates" class="tsd-anchor"></a> <h3 class="tsd-anchor-link"> <span class="tsd-flag ts-flagOptional">Optional</span> trusted<wbr/>Certificates <a href="#trustedCertificates" aria-label="Permalink" class="tsd-anchor-icon"> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-link" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"></path> <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5"></path> <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5"></path> </svg> </a> </h3> <div class="tsd-signature tsd-kind-icon">trusted<wbr/>Certificates<span class="tsd-signature-symbol">?:</span> <span class="tsd-signature-type">string</span><span class="tsd-signature-symbol">[]</span></div> <aside class="tsd-sources"> <p>Inherited from ConnectionUserOptions.trustedCertificates</p> <ul> <li>Defined in <a href="https://github.com/XRPLF/xrpl.js/blob/0f132744/packages/xrpl/src/client/connection.ts#L32">packages/xrpl/src/client/connection.ts:32</a></li> </ul> </aside> </section> </section> </div> <div class="col-4 col-menu menu-sticky-wrap menu-highlight"> <nav class="tsd-navigation primary"> <ul> <li class=""><a href="../modules.html">Exports</a></li> <li class=" tsd-kind-namespace"><a href="../modules/LedgerEntry.html">Ledger<wbr/>Entry</a></li> </ul> </nav> <nav class="tsd-navigation secondary menu-sticky"> <ul> <li class="current tsd-kind-interface"> <a href="ClientOptions.html" class="tsd-kind-icon">Client<wbr/>Options</a> <ul> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#authorization" class="tsd-kind-icon">authorization</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#certificate" class="tsd-kind-icon">certificate</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#connectionTimeout" class="tsd-kind-icon">connection<wbr/>Timeout</a></li> <li class="tsd-kind-property tsd-parent-kind-interface"><a href="ClientOptions.html#feeCushion" class="tsd-kind-icon">fee<wbr/>Cushion</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#headers" class="tsd-kind-icon">headers</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#key" class="tsd-kind-icon">key</a></li> <li class="tsd-kind-property tsd-parent-kind-interface"><a href="ClientOptions.html#maxFeeXRP" class="tsd-kind-icon">max<wbr/>FeeXRP</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#passphrase" class="tsd-kind-icon">passphrase</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-overwrite"><a href="ClientOptions.html#proxy" class="tsd-kind-icon">proxy</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#proxyAuthorization" class="tsd-kind-icon">proxy<wbr/>Authorization</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-overwrite"><a href="ClientOptions.html#timeout" class="tsd-kind-icon">timeout</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#trace" class="tsd-kind-icon">trace</a></li> <li class="tsd-kind-property tsd-parent-kind-interface tsd-is-inherited"><a href="ClientOptions.html#trustedCertificates" class="tsd-kind-icon">trusted<wbr/>Certificates</a></li> </ul> </li> </ul> </nav> </div> </div></div><footer class="with-border-bottom"> <div class="container"> <h2>Legend</h2> <div class="tsd-legend-group"> <ul class="tsd-legend"> <li class="tsd-kind-constructor tsd-parent-kind-class"><span class="tsd-kind-icon">Constructor</span></li> <li class="tsd-kind-property tsd-parent-kind-class"><span class="tsd-kind-icon">Property</span></li> <li class="tsd-kind-method tsd-parent-kind-class"><span class="tsd-kind-icon">Method</span></li> </ul> <ul class="tsd-legend"> <li class="tsd-kind-constructor tsd-parent-kind-class tsd-is-inherited"><span class="tsd-kind-icon">Inherited constructor</span></li> <li class="tsd-kind-property tsd-parent-kind-class tsd-is-inherited"><span class="tsd-kind-icon">Inherited property</span></li> <li class="tsd-kind-method tsd-parent-kind-class tsd-is-inherited"><span class="tsd-kind-icon">Inherited method</span></li> </ul> <ul class="tsd-legend"> <li class="tsd-kind-property tsd-parent-kind-class tsd-is-private"><span class="tsd-kind-icon">Private property</span></li> <li class="tsd-kind-method tsd-parent-kind-class tsd-is-private"><span class="tsd-kind-icon">Private method</span></li> </ul> <ul class="tsd-legend"> <li class="tsd-kind-property tsd-parent-kind-class tsd-is-static"><span class="tsd-kind-icon">Static property</span></li> <li class="tsd-kind-method tsd-parent-kind-class tsd-is-static"><span class="tsd-kind-icon">Static method</span></li> </ul> <ul class="tsd-legend"> <li class="tsd-kind-property tsd-parent-kind-interface"><span class="tsd-kind-icon">Property</span></li> </ul> </div> <h2>Settings</h2> <p> Theme <select id="theme"> <option value="os">OS</option> <option value="light">Light</option> <option value="dark">Dark</option> </select> </p> </div></footer><div class="container tsd-generator"> <p>Generated using <a href="https://typedoc.org/" target="_blank">TypeDoc</a></p></div><div class="overlay"></div><script src="../assets/main.js"></script></body></html>

```

**Comment by intelliot** [comment]
Created #2054 for adding documentation about this feature

**Pull request merged**
