### PR TITLE
feat: NFT support

### PR DESCRIPTION
**Pull request by ledhed2222**
## High Level Overview of Change

WIP adds NFT support

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by ledhed2222** [comment]
TODO:

- tests
- change version to `2.1.0`
- change dependency on ripple-binary-codec to `1.2.0` (not beta)

**Comment by ledhed2222** [comment]
TODO need to confirm error code values/ordering with nik

**Comment by mvadari** [comment]
Can this PR be renamed to something like `feat: NFT support`?

**Review by mvadari — COMMENTED** [review]
add ledger objects

**Review by khancode — APPROVED** [review]
LGTM

**Review by mvadari — APPROVED** [review]

**Pull request merged**
