### PR TITLE
Add basic AMM snippet

### PR DESCRIPTION
**Pull request by JST5000**
## High Level Overview of Change

Add a basic script to use AMM features.

### Context of Change

As part of updating the explorer to handle the new AMMID changes, I need ledger objects to look at. So I wanted to make a little script that could generate them easily, which may as well become a snippet / integration test.

### Type of Change

- [X] Tests (You added tests for code that already exists, or your new feature included in this PR)

## Test Plan

CI Passes and snippets run.

[] Move to the proper folder (For now using javascript file since it's easier to run)

### CODE REVIEW

**Comment by JST5000** [comment]
Currently I'm running into a problem where when I try to run this AMMCreate transaction, it is being rejected by the validation code and I'm not sure why that is: 

```
node test.js           
{
  currency: 'FOO',
  issuer: 'rNvHjSDQiMx8bdVMMnfDdB1atobJdcDqcX',
  value: '10000'
}
TrustSet Response:
 {
  id: 25,
  result: {
    Account: 'raanP2yP1ccziNS9ktbeMtfrsWNU5RyHne',
    Fee: '12',
    Flags: 0,
    LastLedgerSequence: 227979,
    LimitAmount: {
      currency: 'FOO',
      issuer: 'rNvHjSDQiMx8bdVMMnfDdB1atobJdcDqcX',
      value: '10000'
    },
    Sequence: 227959,
    SigningPubKey: 'ED04FC1551AE9DB05A8E4F474EC234A39497CB9ACABE78E895B4FEC77A36467A2F',
    TransactionType: 'TrustSet',
    TxnSignature: '8D2D6D11A3C70D1ECF8059B01F62273032001D9E4114F275380D192B22F9E4D20B4428D4B85D10025131645B296F7D0D0CB392B4EFDE27204E2BCC7582EE6C05',
    date: 746148782,
    hash: 'B700C037BF3BD58803B8B2EAF39DDCCC0D36364A66EED0963A8595C3874194D2',
    inLedger: 227961,
    ledger_index: 227961,
    meta: {
      AffectedNodes: [Array],
      TransactionIndex: 0,
      TransactionResult: 'tesSUCCESS'
    },
    validated: true
  },
  type: 'response'
}
/Users/jmills/Documents/xrpl.js/test/node_modules/xrpl/dist/npm/models/transactions/common.js:87
        throw new errors_1.ValidationError('BaseTransaction: Unknown TransactionType');
              ^

ValidationError: BaseTransaction: Unknown TransactionType
    at validateBaseTransaction (/Users/jmills/Documents/xrpl.js/test/node_modules/xrpl/dist/npm/models/transactions/common.js:87:15)
    at validateAMMCreate (/Users/jmills/Documents/xrpl.js/test/node_modules/xrpl/dist/npm/models/transactions/AMMCreate.js:8:42)
    at validate (/Users/jmills/Documents/xrpl.js/test/node_modules/xrpl/dist/npm/models/transactions/transaction.js:66:47)
    at Wallet.sign (/Users/jmills/Documents/xrpl.js/test/node_modules/xrpl/dist/npm/Wallet/index.js:123:37)
    at /Users/jmills/Documents/xrpl.js/test/node_modules/xrpl/dist/npm/sugar/submit.js:107:23
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jmills/Documents/xrpl.js/test/node_modules/xrpl/dist/npm/sugar/submit.js:5:58) {
  data: undefined
}
```

I've tried with versions `2.9.0-beta.0` and `2.8.1-beta.0` with both giving the same error. (The latest main release of xrpl.js does not have AMM yet - pending next release)

**Comment by mvadari** [comment]
I'm confused about why this is being added to xrpl.js - I thought @khancode was already working on integration tests.

**Comment by JST5000** [comment]
> I'm confused about why this is being added to xrpl.js - I thought @khancode was already working on integration tests.

He is, I was thinking a snippet in the `snippets` folder could be handy though as something to just copy / paste / run as opposed to something which has to be run as part of tests. 

I had to write the code anyway since I wanted to get an AMM object and didn't know there was a handy lookup for it before writing this code . It was also handy to make the PR so @khancode could try reproducing the problem I ran into locally.

This is the handy lookup by the way if curious:
```
{
  "type": "amm",
  "command": "ledger_data"
}
```

**Comment by JST5000** [comment]
Not worth the time to move this into a full documented snippet currently. May potentially re-open later once the AMM changes are formally proposed.

**Pull request closed without merging**
