### PR TITLE
update Paths snippet test

### PR DESCRIPTION
**Pull request by ckeshava**
perform prerequisite test setup within the test, remove dependence on the external state of testnet

## High Level Overview of Change
This is the sister PR for https://github.com/XRPLF/xrpl-py/pull/739. Please check that PR for more context.

### Context of Change
The paths snippet tests depends on several test net accounts for its functionality. This PR aims to remove such dependencies. The requirements of the test are setup within the test itself. This causes less disruptions to the CI/CD pipelines after testnet resets.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### Did you update HISTORY.md?

- [ ] Yes
- [x] No, this change does not impact library users

## Summary by CodeRabbit

- **New Features**
	- Enhanced pathfinding test functionality for issued currencies on the XRPL.
	- Introduced a more structured testing setup with multiple wallets and trust lines.
	- Improved pathfinding requests to allow for currency transfers beyond XRP.

- **Bug Fixes**
	- Enhanced response handling to validate paths and source amounts accurately.

### CODE REVIEW

**Review by mvadari — COMMENTED** [review]
Why make this snippet way more complicated?

**Comment by ckeshava** [comment]
This was the easiest design that I could find, to demonstrate the use of `path_find` request. The existing code is broken, it warrants manual intervention after every test net reset.

**Comment by justinr1234** [comment]
@coderabbit full review

**Comment by justinr1234** [comment]
@coderabbitai full review

**Comment by ckeshava** [comment]
I had to merge these changes into this PR as well: https://github.com/XRPLF/xrpl.js/pull/2773 The CI/CD is not passing without the Paths changes. 

Once this PR is approved, I can merge the bridge_snippet PR and close this PR.

**Review by justinr1234 — APPROVED** [review]

**Pull request merged**
