### PR TITLE
XLS80d PermissionedDomains

### PR DESCRIPTION
**Pull request by ckeshava**
## High Level Overview of Change

This PR implements the XLS-80d specification titled "PermissionedDomains": https://github.com/XRPLF/XRPL-Standards/discussions/228

Here is the accompanying xrpl-py implementation: https://github.com/XRPLF/xrpl-py/pull/773

This PR has the following dependencies. The final merge needs to await the below two PRs:
- Reference C++ Implementation: https://github.com/XRPLF/rippled/pull/5161
- xrpl.js implementation of the Credentials feature: #2829 

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### Did you update HISTORY.md?

- [x] Yes
- [ ] No, this change does not impact library users

## Test Plan
I've included unit and integration tests

### CODE REVIEW

**Comment by mvadari** [comment]
@achowdhry-ripple why was this PR closed?

**Comment by achowdhry-ripple** [comment]
Ah think this was working off of the credentials xls 70 branch, which i just merged in so this auto closed. Didn't mean to

**Comment by achowdhry-ripple** [comment]
Not sure how to reopen this @ckeshava

**Comment by mvadari** [comment]
TIL PRs autoclose - never seen that before

**Comment by ckeshava** [comment]
continued via https://github.com/XRPLF/xrpl.js/pull/2874

**Pull request closed without merging**
